# wrangler.toml
name = "social-relay-web"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-11-13"

[git]
repo = "mahoulabs/social-relay"
branch = "main"